### ISSUE TITLE
Navigating to folders with a `-` does not work

### ISSUE THREAD

**Issue by stefan131** [hugovandevliert/vim-life#1]
Navigating to a child folder does not work when the path contains a  dash (`-`).
Instead it will show a black screen, pressing the `-` key again to navigate further back works.

Example:
Path = `~/repositories/vim-life/plugin`
Press `-` to navigate back, works. Path = `~/repositories/vim-life`
Navigate to `plugin` again, results in black screen
Press `-` to navigate back, works. Path = `~/repositories`

**Comment by hugovandevliert** [comment]
Thanks for the example @stefan131! Could you verify if 936ae09981d69a80499271e36722d8f16b8fdd1d fixed the issue for you?

**Comment by stefan131** [comment]
It did, thanks! 😄
That was _really_ quick
